services:
  mongodb:
    image: mongo:7
    ports:
      - "127.0.0.1:27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"

  backend:
    build: ./trial-backend
    ports:
      - "5000:5000"
    env_file:
      - ./trial-backend/.env
    environment:
      - MONGO_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/trial-project?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  frontend:
    build: ./trial-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    profiles:
      - local

volumes:
  mongo_data: {}